build:
  nodes:
    coverage:
      environment:
        node: '16.3.0'
      tests:
        override:
          - command: 'npm install'
    analysis:
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
          - command: 'npm install'

filter:
  excluded_paths:
    - tests/
  dependency_paths:
    - vendor/

tools:
  external_code_coverage:
    timeout: 600
