language: php

os:
  - linux

dist: xenial

php:
  - 8.0

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

env:
  global:
    - XDEBUG_MODE=coverage

install:
  - composer install --no-interaction
  - composer require --dev php-coveralls/php-coveralls

before_script:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE bcadenpasar_chatbot'
  - php artisan key:generate
  - php artisan migrate --no-interaction -vvv

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
